server:
  port: 9191 
  
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/paymentdb
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
      application:    name: PAYMENT-SERVICE
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true   
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
      hostname: localhost    