server:
  port: 9192 
  
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/orderdb
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    application:    name: ORDER-SERVICE
    
eureka:  client:    register-with-eureka: true
    fetch-registry: true   
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
      hostname: localhost
           
                  